### ISSUE TITLE
Watson Analytics Data Upload Error

### ISSUE THREAD

**Issue by HappyAWolf** [TalkData2Me/SLMR#3]
I was trying to load the data to Watson Analytics but got the following error message: 
"The dataset contains too many columns. Please remove some and try again."

It seems that we may either use AWS or run it on a single machine with large RAM.

**Comment by evgenymun** [comment]
It seems that AWS free version has only 1GB of RAM.

**Comment by HappyAWolf** [comment]
A service ticket has been submitted to IBM, ticket number 5377-12030944. 
Not expecting any solution from them immediately, I'm just to test if any alternative platform would work.

**Comment by HappyAWolf** [comment]
Just found out that there is a limit of 500 columns in Watson Analytics professional account. 
This concludes the trial of the IBM analytic tool with a failure on our project.

**Comment by HappyAWolf** [comment]
Just got the response from the IBM Analytics Solutions Support, which confirmed the limitation of Watson Analytics:

"Thank you for contacting the IBM Watson Analytics Support team. With regards to your issue, the maximum number of columns for a WA Professional subscription is 500, as you have already found out. At this stage, there are no methods available that can merge multiple datasets within Watson Analytics. The 500 column limit is hard coded against your subscription level and there are no workarounds to avoid it. The only way to upload your data is to reduce the amount of columns before uploading into WA. Please let me know if you need further assistance."
